"""
This type stub file was generated by pyright.
"""

import glob
import os
import pprint
import re
import shutil
import tarfile
from urllib.request import urlretrieve

"""
    pygments.lexers._php_builtins
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    This file loads the function names and their modules from the
    php webpage and generates itself.

    Run with `python -I` to regenerate.

    :copyright: Copyright 2006-2023 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
"""
MODULES = ...
if __name__ == '__main__':
    PHP_MANUAL_URL = ...
    PHP_MANUAL_DIR = ...
    PHP_REFERENCE_GLOB = ...
    PHP_FUNCTION_RE = ...
    PHP_MODULE_RE = ...
    def get_php_functions(): # -> dict[Unknown, Unknown]:
        ...
    
    def get_php_references(): # -> Generator[str, None, None]:
        ...
    
    def regenerate(filename, modules): # -> None:
        ...
    
    def run(): # -> None:
        ...
    
