"""
This type stub file was generated by pyright.
"""

"""DNS rdata type classes"""
__all__ = ["ANY", "IN", "CH", "dnskeybase", "dsbase", "euibase", "mxbase", "nsbase", "svcbbase", "tlsabase", "txtbase", "util"]
