"""
This type stub file was generated by pyright.
"""

import os
import typing
from cryptography import exceptions, utils
from cryptography.hazmat.backends.openssl import aead
from cryptography.hazmat.backends.openssl.backend import backend

class ChaCha20Poly1305:
    _MAX_SIZE = 2 ** 32
    def __init__(self, key: bytes) -> None:
        ...
    
    @classmethod
    def generate_key(cls) -> bytes:
        ...
    
    def encrypt(self, nonce: bytes, data: bytes, associated_data: typing.Optional[bytes]) -> bytes:
        ...
    
    def decrypt(self, nonce: bytes, data: bytes, associated_data: typing.Optional[bytes]) -> bytes:
        ...
    


class AESCCM:
    _MAX_SIZE = 2 ** 32
    def __init__(self, key: bytes, tag_length: int = ...) -> None:
        ...
    
    @classmethod
    def generate_key(cls, bit_length: int) -> bytes:
        ...
    
    def encrypt(self, nonce: bytes, data: bytes, associated_data: typing.Optional[bytes]) -> bytes:
        ...
    
    def decrypt(self, nonce: bytes, data: bytes, associated_data: typing.Optional[bytes]) -> bytes:
        ...
    


class AESGCM:
    _MAX_SIZE = 2 ** 32
    def __init__(self, key: bytes) -> None:
        ...
    
    @classmethod
    def generate_key(cls, bit_length: int) -> bytes:
        ...
    
    def encrypt(self, nonce: bytes, data: bytes, associated_data: typing.Optional[bytes]) -> bytes:
        ...
    
    def decrypt(self, nonce: bytes, data: bytes, associated_data: typing.Optional[bytes]) -> bytes:
        ...
    


