"""
This type stub file was generated by pyright.
"""

import cherrypy
import os
from cherrypy import tools, url

"""<MyProject>, a CherryPy application.

Use this as a base for creating new CherryPy applications. When you want
to make a new app, copy and paste this folder to some other location
(maybe site-packages) and rename it to the name of your project,
then tweak as desired.

Even before any tweaking, this should serve a few demonstration pages.
Change to this directory and run:

    cherryd -c site.conf

"""
local_dir = ...
@cherrypy.config(**{ 'tools.log_tracebacks.on': True })
class Root:
    """Declaration of the CherryPy app URI structure."""
    @cherrypy.expose
    def index(self): # -> str:
        """Render HTML-template at the root path of the web-app."""
        ...
    
    @cherrypy.expose
    def default(self, *args, **kwargs): # -> str:
        """Render catch-all args and kwargs."""
        ...
    
    @cherrypy.expose
    def other(self, a=..., b=..., c=...): # -> str:
        """Render number of fruits based on third argument."""
        ...
    
    files = ...


root = ...
