"""
This type stub file was generated by pyright.
"""

import typing
from cryptography.hazmat._types import _PRIVATE_KEY_TYPES, _PUBLIC_KEY_TYPES
from cryptography.hazmat.backends import _get_backend
from cryptography.hazmat.primitives.asymmetric import dh

def load_pem_private_key(data: bytes, password: typing.Optional[bytes], backend=...) -> _PRIVATE_KEY_TYPES:
    ...

def load_pem_public_key(data: bytes, backend=...) -> _PUBLIC_KEY_TYPES:
    ...

def load_pem_parameters(data: bytes, backend=...) -> dh.DHParameters:
    ...

def load_der_private_key(data: bytes, password: typing.Optional[bytes], backend=...) -> _PRIVATE_KEY_TYPES:
    ...

def load_der_public_key(data: bytes, backend=...) -> _PUBLIC_KEY_TYPES:
    ...

def load_der_parameters(data: bytes, backend=...) -> dh.DHParameters:
    ...

