"""
This type stub file was generated by pyright.
"""

import cheroot.server

"""Native adapter for serving CherryPy via its builtin server."""
class NativeGateway(cheroot.server.Gateway):
    """Native gateway implementation allowing to bypass WSGI."""
    recursive = ...
    def respond(self): # -> None:
        """Obtain response from CherryPy machinery and then send it."""
        ...
    
    def send_response(self, status, headers, body): # -> None:
        """Send response to HTTP request."""
        ...
    


class CPHTTPServer(cheroot.server.HTTPServer):
    """Wrapper for cheroot.server.HTTPServer.

    cheroot has been designed to not reference CherryPy in any way,
    so that it can be used in other frameworks and applications.
    Therefore, we wrap it here, so we can apply some attributes
    from config -> cherrypy.server -> HTTPServer.
    """
    def __init__(self, server_adapter=...) -> None:
        """Initialize CPHTTPServer."""
        ...
    


