"""
This type stub file was generated by pyright.
"""

"""
JSON support.

Expose preferred json module as json and provide encode/decode
convenience functions.
"""
__all__ = ['json', 'encode', 'decode']
decode = ...
_encode = ...
def encode(value): # -> Generator[bytes, None, None]:
    """Encode to bytes."""
    ...

