"""
This type stub file was generated by pyright.
"""

"""The CherryPy daemon."""
def start(configfiles=..., daemonize=..., environment=..., fastcgi=..., scgi=..., pidfile=..., imports=..., cgi=...): # -> None:
    """Subscribe all engine plugins and start the engine."""
    ...

def run(): # -> None:
    """Run cherryd CLI."""
    ...

