"""
This type stub file was generated by pyright.
"""

from cryptography import utils

class ObjectIdentifier:
    def __init__(self, dotted_string: str) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    
    dotted_string = ...


