"""
This type stub file was generated by pyright.
"""

import abc

class AsymmetricPadding(metaclass=abc.ABCMeta):
    @abc.abstractproperty
    def name(self) -> str:
        """
        A string naming this padding (e.g. "PSS", "PKCS1").
        """
        ...
    


