"""
This type stub file was generated by pyright.
"""

import os
import sys

"""
Regression test suite for CherryPy.
"""
def newexit():
    ...

def setup(): # -> None:
    ...

def teardown(): # -> None:
    ...

