"""
This type stub file was generated by pyright.
"""

import sys
from cryptography import utils
from cryptography.exceptions import AlreadyFinalized, InvalidKey, UnsupportedAlgorithm, _Reasons
from cryptography.hazmat.backends import _get_backend
from cryptography.hazmat.backends.interfaces import ScryptBackend
from cryptography.hazmat.primitives import constant_time
from cryptography.hazmat.primitives.kdf import KeyDerivationFunction

_MEM_LIMIT = ...
class Scrypt(KeyDerivationFunction):
    def __init__(self, salt: bytes, length: int, n: int, r: int, p: int, backend=...) -> None:
        ...
    
    def derive(self, key_material: bytes) -> bytes:
        ...
    
    def verify(self, key_material: bytes, expected_key: bytes) -> None:
        ...
    


